In [6]:
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px


# ----- need to convert yearly data into a better way

In [7]:
# load in data
df = pd.read_csv("medicare_with_conditions.csv")
df.shape

(14309, 48)

In [8]:
df.head(10)

,Brnd_Name,Gnrc_Name,Tot_Mftr,Mftr_Name,Tot_Spndng_2019,Tot_Dsg_Unts_2019,Tot_Clms_2019,Tot_Benes_2019,Avg_Spnd_Per_Dsg_Unt_Wghtd_2019,Avg_Spnd_Per_Clm_2019,...,Tot_Clms_2023,Tot_Benes_2023,Avg_Spnd_Per_Dsg_Unt_Wghtd_2023,Avg_Spnd_Per_Clm_2023,Avg_Spnd_Per_Bene_2023,Outlier_Flag_2023,Chg_Avg_Spnd_Per_Dsg_Unt_22_23,CAGR_Avg_Spnd_Per_Dsg_Unt_19_23,ATC_Codes,Disease_Category
0,1st Tier Unifine Pentips,"Pen Needle, Diabetic",1,Overall,139201.68,642471.0,5392.0,1878.0,0.216788,25.816335,...,1613,699.0,0.227162,27.498475,63.454993,0.0,0.005702,0.011754,NaN,Other / Not classified
1,1st Tier Unifine Pentips,"Pen Needle, Diabetic",1,Owen Mumford Us,139201.68,642471.0,5392.0,1878.0,0.216788,25.816335,...,1613,699.0,0.227162,27.498475,63.454993,0.0,0.005702,0.011754,NaN,Other / Not classified
2,1st Tier Unifine Pentips Plus,"Pen Needle, Diabetic",1,Overall,343031.42,1830596.0,14581.0,5319.0,0.187389,23.525919,...,3269,1267.0,0.240932,29.963652,77.309534,0.0,0.022165,0.064848,NaN,Other / Not classified
3,1st Tier Unifine Pentips Plus,"Pen Needle, Diabetic",1,Owen Mumford Us,343031.42,1830596.0,14581.0,5319.0,0.187389,23.525919,...,3269,1267.0,0.240932,29.963652,77.309534,0.0,0.022165,0.064848,NaN,Other / Not classified
4,Abacavir,Abacavir Sulfate,5,Overall,10110328.45,3316293.0,42629.0,6085.0,3.482725,237.170200,...,19632,2809.0,3.594357,269.320263,1882.269637,0.0,-0.071481,0.007919,J05AF,Other / Not classified
5,Abacavir,Abacavir Sulfate,1,"Cipla USA, Inc.",698311.33,192395.0,3311.0,698.0,3.629571,210.906472,...,2943,594.0,2.884791,241.434383,1196.197626,0.0,-0.031308,-0.055798,J05AF,Other / Not classified
6,Abacavir,Abacavir Sulfate,1,Rising Pharm,142257.84,312210.0,433.0,77.0,0.455648,328.540046,...,206,31.0,0.442093,237.740631,1579.824839,0.0,-0.058313,-0.007522,J05AF,Other / Not classified
7,Abacavir,Abacavir Sulfate,1,Mylan,1937920.78,500896.0,7984.0,1505.0,3.868908,242.725549,...,2470,469.0,3.854489,269.920324,1421.542004,0.0,-0.123765,-0.000933,J05AF,Other / Not classified
8,Abacavir,Abacavir Sulfate,1,Aurobindo Pharm,3097563.43,836918.0,13106.0,2299.0,3.701155,236.346973,...,6035,965.0,3.568940,233.883569,1462.681181,0.0,-0.094260,-0.009053,J05AF,Other / Not classified
9,Abacavir,Abacavir Sulfate,1,Camber Pharmace,4234275.07,1473874.0,17795.0,3305.0,3.194918,237.947461,...,7978,1433.0,3.876191,307.042982,1709.413057,0.0,-0.052507,0.049510,J05AF,Other / Not classified

In [9]:
# filter & focus on 2023 data & overall data  
outlier_23_df = df[df['Outlier_Flag_2023'] == 1]
outlier_23_df

,Brnd_Name,Gnrc_Name,Tot_Mftr,Mftr_Name,Tot_Spndng_2019,Tot_Dsg_Unts_2019,Tot_Clms_2019,Tot_Benes_2019,Avg_Spnd_Per_Dsg_Unt_Wghtd_2019,Avg_Spnd_Per_Clm_2019,...,Tot_Clms_2023,Tot_Benes_2023,Avg_Spnd_Per_Dsg_Unt_Wghtd_2023,Avg_Spnd_Per_Clm_2023,Avg_Spnd_Per_Bene_2023,Outlier_Flag_2023,Chg_Avg_Spnd_Per_Dsg_Unt_22_23,CAGR_Avg_Spnd_Per_Dsg_Unt_19_23,ATC_Codes,Disease_Category
21,Abilify Mycite,Aripiprazole,1,Overall,40552.86,720.0,24.0,NaN,56.323417,1689.702500,...,44,NaN,57.119136,1713.574091,NaN,1.0,-0.002723,0.003513,N05AX,Other / Not classified
22,Abilify Mycite,Aripiprazole,1,Otsuka America,40552.86,720.0,24.0,NaN,56.323417,1689.702500,...,44,NaN,57.119136,1713.574091,NaN,1.0,-0.002723,0.003513,N05AX,Other / Not classified
30,Abiraterone Acetate,Abiraterone Acetate,1,Florida Pharmac,NaN,NaN,NaN,NaN,NaN,NaN,...,11038,4473.0,17.896072,1861.152127,4592.755909,1.0,9.749039,9.749039,L01XK|L02BX,Other / Not classified
34,Abiraterone Acetate,Abiraterone Acetate,1,Novadoz Pharmac,20635781.20,564258.0,4957.0,2138.0,36.571535,4162.957676,...,104009,23225.0,19.197882,2153.912292,9645.910164,1.0,-0.182005,-0.148808,L01XK|L02BX,Other / Not classified
39,Abiraterone Acetate,Abiraterone Acetate,1,Glenmark Pharma,NaN,NaN,NaN,NaN,NaN,NaN,...,23428,7724.0,29.436415,2548.326564,7729.440023,1.0,-0.130599,0.154831,L01XK|L02BX,Other / Not classified
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14291,Zynlonta,Loncastuximab Tesirine-Lpyl,1,Overall,NaN,NaN,NaN,NaN,NaN,NaN,...,22,NaN,25958.690000,30678.451820,NaN,1.0,0.040768,0.040768,L01FX,Other / Not classified
14292,Zynlonta,Loncastuximab Tesirine-Lpyl,1,Adc Therapeutic,NaN,NaN,NaN,NaN,NaN,NaN,...,22,NaN,25958.690000,30678.451820,NaN,1.0,0.040768,0.040768,L01FX,Other / Not classified
14304,Zyvox,Linezolid,1,Overall,652488.55,5419.0,110.0,69.0,213.322618,5931.714091,...,30,26.0,74.755015,1669.528667,1926.379231,1.0,-0.138851,-0.230602,J01XX,Other / Not classified
14305,Zyvox,Linezolid,1,Pharmacia-Upjhn,652488.55,5419.0,110.0,69.0,213.322618,5931.714091,...,30,26.0,74.755015,1669.528667,1926.379231,1.0,-0.138851,-0.230602,J01XX,Other / Not classified
14308,Zyvox,Linezolid In Dextrose 5%,1,Phar-Prep/Pfize,19122.83,110400.0,44.0,20.0,0.173214,434.609773,...,26,NaN,0.153137,284.480769,NaN,1.0,-0.086898,-0.030330,NaN,Other / Not classified

In [10]:
outlier_23_df.columns

Index(['Brnd_Name', 'Gnrc_Name', 'Tot_Mftr', 'Mftr_Name', 'Tot_Spndng_2019',
       'Tot_Dsg_Unts_2019', 'Tot_Clms_2019', 'Tot_Benes_2019',
       'Avg_Spnd_Per_Dsg_Unt_Wghtd_2019', 'Avg_Spnd_Per_Clm_2019',
       'Avg_Spnd_Per_Bene_2019', 'Outlier_Flag_2019', 'Tot_Spndng_2020',
       'Tot_Dsg_Unts_2020', 'Tot_Clms_2020', 'Tot_Benes_2020',
       'Avg_Spnd_Per_Dsg_Unt_Wghtd_2020', 'Avg_Spnd_Per_Clm_2020',
       'Avg_Spnd_Per_Bene_2020', 'Outlier_Flag_2020', 'Tot_Spndng_2021',
       'Tot_Dsg_Unts_2021', 'Tot_Clms_2021', 'Tot_Benes_2021',
       'Avg_Spnd_Per_Dsg_Unt_Wghtd_2021', 'Avg_Spnd_Per_Clm_2021',
       'Avg_Spnd_Per_Bene_2021', 'Outlier_Flag_2021', 'Tot_Spndng_2022',
       'Tot_Dsg_Unts_2022', 'Tot_Clms_2022', 'Tot_Benes_2022',
       'Avg_Spnd_Per_Dsg_Unt_Wghtd_2022', 'Avg_Spnd_Per_Clm_2022',
       'Avg_Spnd_Per_Bene_2022', 'Outlier_Flag_2022', 'Tot_Spndng_2023',
       'Tot_Dsg_Unts_2023', 'Tot_Clms_2023', 'Tot_Benes_2023',
       'Avg_Spnd_Per_Dsg_Unt_Wghtd_2023', 'Avg_Spnd_Per_Clm_2023',
       'Avg_Spnd_Per_Bene_2023', 'Outlier_Flag_2023',
       'Chg_Avg_Spnd_Per_Dsg_Unt_22_23', 'CAGR_Avg_Spnd_Per_Dsg_Unt_19_23',
       'ATC_Codes', 'Disease_Category'],
      dtype='object')

In [11]:
fig = px.scatter(outlier_23_df[outlier_23_df['Mftr_Name'] == 'Overall'], x='Avg_Spnd_Per_Clm_2023', y='Tot_Spndng_2023',
                 hover_data=['Brnd_Name', 'Gnrc_Name', 'Mftr_Name'])

fig.update_layout(
    title='Average Spend per Claim vs Total Spending in 2023 (Overall)',
)

fig.show()

In [12]:
# stacked bar chart to show brand vs generic name
overall_df = df[df['Mftr_Name'] == 'Overall']

# create a new column for brand vs generic drug
drug_types = []
for i in range(len(overall_df)):
    if overall_df.iloc[i]['Brnd_Name'] != overall_df.iloc[i]['Gnrc_Name']:
        drug_types.append('Brand')
    else:
        drug_types.append('Generic')

overall_df['Drug_Types'] = drug_types

# find total spending by year and drug type (brand vs generic)
lst = []
for year in [2019, 2020, 2021, 2022, 2023]:
    total_spending_year = 'Tot_Spndng_' + str(year)
    
    brand_total = overall_df[overall_df['Drug_Types'] == 'Brand'][total_spending_year].sum()
    generic_total = overall_df[overall_df['Drug_Types'] == 'Generic'][total_spending_year].sum()
    
    lst.append({'Year': year, 'Drug_Types': 'Brand', 'Total Spending': brand_total})
    lst.append({'Year': year, 'Drug_Types': 'Generic', 'Total Spending': generic_total})

plot_df = pd.DataFrame(lst)

fig = px.bar(plot_df, x='Year', y='Total Spending', color='Drug_Types', barmode='stack')

fig.update_layout(title='Total Medicare Spending Each Year by Brand vs Generic Name From 2019-2023')

fig.show()

/var/folders/r8/m_tx_xf91g7fj_3mwpbc_pkm0000gn/T/ipykernel_48289/1300707661.py:12: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [13]:
#first remove NaN values
outlier_23_df = outlier_23_df.dropna(subset=['Mftr_Name']) # remove NaN values in Mftr_Name column
outlier_23_df = outlier_23_df[outlier_23_df['Mftr_Name'] != 'Overall'] # remove rows where Mftr_Name is 'Overall'
outlier_23_df

,Brnd_Name,Gnrc_Name,Tot_Mftr,Mftr_Name,Tot_Spndng_2019,Tot_Dsg_Unts_2019,Tot_Clms_2019,Tot_Benes_2019,Avg_Spnd_Per_Dsg_Unt_Wghtd_2019,Avg_Spnd_Per_Clm_2019,...,Tot_Clms_2023,Tot_Benes_2023,Avg_Spnd_Per_Dsg_Unt_Wghtd_2023,Avg_Spnd_Per_Clm_2023,Avg_Spnd_Per_Bene_2023,Outlier_Flag_2023,Chg_Avg_Spnd_Per_Dsg_Unt_22_23,CAGR_Avg_Spnd_Per_Dsg_Unt_19_23,ATC_Codes,Disease_Category
22,Abilify Mycite,Aripiprazole,1,Otsuka America,40552.86,720.0,24.0,NaN,56.323417,1689.702500,...,44,NaN,57.119136,1713.574091,NaN,1.0,-0.002723,0.003513,N05AX,Other / Not classified
30,Abiraterone Acetate,Abiraterone Acetate,1,Florida Pharmac,NaN,NaN,NaN,NaN,NaN,NaN,...,11038,4473.0,17.896072,1861.152127,4592.755909,1.0,9.749039,9.749039,L01XK|L02BX,Other / Not classified
34,Abiraterone Acetate,Abiraterone Acetate,1,Novadoz Pharmac,20635781.20,564258.0,4957.0,2138.0,36.571535,4162.957676,...,104009,23225.0,19.197882,2153.912292,9645.910164,1.0,-0.182005,-0.148808,L01XK|L02BX,Other / Not classified
39,Abiraterone Acetate,Abiraterone Acetate,1,Glenmark Pharma,NaN,NaN,NaN,NaN,NaN,NaN,...,23428,7724.0,29.436415,2548.326564,7729.440023,1.0,-0.130599,0.154831,L01XK|L02BX,Other / Not classified
42,Abiraterone Acetate,Abiraterone Acetate,1,Teva USA,11777466.40,236279.0,2016.0,679.0,49.845591,5841.997222,...,365,76.0,34.832567,3798.546137,18243.017630,1.0,0.172911,-0.085698,L01XK|L02BX,Other / Not classified
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14263,Zorvolex,Diclofenac Submicronized,1,Egalet/Zyla Lif,808084.48,112745.0,1212.0,653.0,7.167617,666.736370,...,18,NaN,8.822025,313.693333,NaN,1.0,0.022673,0.053291,NaN,Other / Not classified
14282,Zyclara,Imiquimod,1,Bausch Health U,617490.69,9520.5,477.0,342.0,88.745150,1294.529748,...,90,69.0,140.145017,1278.635556,1667.785507,1.0,0.035661,0.121007,D06BB,Other / Not classified
14292,Zynlonta,Loncastuximab Tesirine-Lpyl,1,Adc Therapeutic,NaN,NaN,NaN,NaN,NaN,NaN,...,22,NaN,25958.690000,30678.451820,NaN,1.0,0.040768,0.040768,L01FX,Other / Not classified
14305,Zyvox,Linezolid,1,Pharmacia-Upjhn,652488.55,5419.0,110.0,69.0,213.322618,5931.714091,...,30,26.0,74.755015,1669.528667,1926.379231,1.0,-0.138851,-0.230602,J01XX,Other / Not classified
14308,Zyvox,Linezolid In Dextrose 5%,1,Phar-Prep/Pfize,19122.83,110400.0,44.0,20.0,0.173214,434.609773,...,26,NaN,0.153137,284.480769,NaN,1.0,-0.086898,-0.030330,NaN,Other / Not classified

In [14]:
# average growth rate of drug spending per year by Manufacturer 2019-2023
df['Spndng_Growth_2023'] = (df['Tot_Spndng_2023'] - df['Tot_Spndng_2022']) / df['Tot_Spndng_2022']
df['Spndng_Growth_2022'] = (df['Tot_Spndng_2022'] - df['Tot_Spndng_2021']) / df['Tot_Spndng_2021']
df['Spndng_Growth_2021'] = (df['Tot_Spndng_2021'] - df['Tot_Spndng_2020']) / df['Tot_Spndng_2020']
df['Spndng_Growth_2020'] = (df['Tot_Spndng_2020'] - df['Tot_Spndng_2019']) / df['Tot_Spndng_2019']
df['Avg_Spndng_Growth'] = df[['Spndng_Growth_2023', 'Spndng_Growth_2022', 'Spndng_Growth_2021', 'Spndng_Growth_2020']].mean(axis=1)

# Sort the dataframe by Manufacturer Name
df = df.sort_values(by='Mftr_Name')


fig = px.bar(df, 
             x='Mftr_Name',  
             y='Avg_Spndng_Growth', 
             hover_data=['Brnd_Name', 'Gnrc_Name', 'Mftr_Name'])

fig.update_layout(
    xaxis=dict(
        title='Manufacturer Name',
        tickangle=-45,
        automargin=True,
        rangeslider=dict(visible=True)  # Add a range slider for scrollable x-axis
    ),
    height=1000,
    width=2000,
    xaxis_title='Manufacturer Name',
    yaxis_title='Average Spending Growth Rate'
)
fig.update_layout(
    title='Average Spending Growth Rate (2020-2023) by Manufacturer',
    height=1000,
    width=2000,
)
fig.show()

In [15]:
#check data columns to prepare for cleaning
df.columns.to_list()

['Brnd_Name',
 'Gnrc_Name',
 'Tot_Mftr',
 'Mftr_Name',
 'Tot_Spndng_2019',
 'Tot_Dsg_Unts_2019',
 'Tot_Clms_2019',
 'Tot_Benes_2019',
 'Avg_Spnd_Per_Dsg_Unt_Wghtd_2019',
 'Avg_Spnd_Per_Clm_2019',
 'Avg_Spnd_Per_Bene_2019',
 'Outlier_Flag_2019',
 'Tot_Spndng_2020',
 'Tot_Dsg_Unts_2020',
 'Tot_Clms_2020',
 'Tot_Benes_2020',
 'Avg_Spnd_Per_Dsg_Unt_Wghtd_2020',
 'Avg_Spnd_Per_Clm_2020',
 'Avg_Spnd_Per_Bene_2020',
 'Outlier_Flag_2020',
 'Tot_Spndng_2021',
 'Tot_Dsg_Unts_2021',
 'Tot_Clms_2021',
 'Tot_Benes_2021',
 'Avg_Spnd_Per_Dsg_Unt_Wghtd_2021',
 'Avg_Spnd_Per_Clm_2021',
 'Avg_Spnd_Per_Bene_2021',
 'Outlier_Flag_2021',
 'Tot_Spndng_2022',
 'Tot_Dsg_Unts_2022',
 'Tot_Clms_2022',
 'Tot_Benes_2022',
 'Avg_Spnd_Per_Dsg_Unt_Wghtd_2022',
 'Avg_Spnd_Per_Clm_2022',
 'Avg_Spnd_Per_Bene_2022',
 'Outlier_Flag_2022',
 'Tot_Spndng_2023',
 'Tot_Dsg_Unts_2023',
 'Tot_Clms_2023',
 'Tot_Benes_2023',
 'Avg_Spnd_Per_Dsg_Unt_Wghtd_2023',
 'Avg_Spnd_Per_Clm_2023',
 'Avg_Spnd_Per_Bene_2023',
 'Outlier_Flag_2023',
 'Chg_Avg_Spnd_Per_Dsg_Unt_22_23',
 'CAGR_Avg_Spnd_Per_Dsg_Unt_19_23',
 'ATC_Codes',
 'Disease_Category']

In [17]:
#filter to "overall" manufacturer for pricing analysis
overall_df = df[df['Mftr_Name'] == 'Overall']
overall_df

,Brnd_Name,Gnrc_Name,Tot_Mftr,Mftr_Name,Tot_Spndng_2019,Tot_Dsg_Unts_2019,Tot_Clms_2019,Tot_Benes_2019,Avg_Spnd_Per_Dsg_Unt_Wghtd_2019,Avg_Spnd_Per_Clm_2019,...,Outlier_Flag_2023,Chg_Avg_Spnd_Per_Dsg_Unt_22_23,CAGR_Avg_Spnd_Per_Dsg_Unt_19_23,ATC_Codes,Disease_Category,Spndng_Growth_2023,Spndng_Growth_2022,Spndng_Growth_2021,Spndng_Growth_2020,Avg_Spndng_Growth
9261,Nivestym*,Filgrastim-Aafi,1,Overall,178392.01,408.3,113.0,37.0,441.319845,1578.690354,...,0.0,-0.053041,-0.104698,L03AA,Other / Not classified,0.978193,1.751759,0.895201,7.218722,2.710969
13308,Ultra Comfort,"Syringe And Needle,Insulin,1ml",2,Overall,216029.48,1006843.0,8029.0,3264.0,0.208316,26.906150,...,0.0,-0.000186,0.013618,NaN,Other / Not classified,-0.272348,-0.663279,-0.343582,-0.485491,-0.441175
9259,Niva-Plus,Multivit-Mins60/Iron Fum/Folic,1,Overall,3459.83,8450.0,227.0,112.0,0.409447,15.241542,...,0.0,-0.002691,0.145688,NaN,Other / Not classified,-0.561138,-0.181944,0.231866,15.970230,3.864754
9263,Nizatidine,Nizatidine,1,Overall,553505.69,951062.0,10446.0,11751.0,0.598778,52.987334,...,0.0,0.232727,0.279070,A02BA,Other / Not classified,4.953660,5.467883,-0.972316,-0.463306,2.246480
9255,Nityr,Nitisinone,1,Overall,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.040681,A16AX,Other / Not classified,NaN,NaN,7.927063,NaN,7.927063
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7633,Lofena,Diclofenac Potassium,1,Overall,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,-0.046959,-0.046959,D11AX|M01AB|M02AA|S01BC,Arthritis,0.810767,NaN,NaN,NaN,0.810767
1324,Bentyl,Dicyclomine HCl,1,Overall,30668.79,704.0,41.0,14.0,43.563622,748.019268,...,1.0,-0.586787,-0.197487,NaN,Other / Not classified,2.613685,0.075692,-0.415367,-0.269959,0.501013
1316,Benicar,Olmesartan Medoxomil,2,Overall,22300006.70,2646824.0,49873.0,13206.0,8.550539,447.135859,...,0.0,0.120575,0.063864,C09CA,Hypertension,-0.029326,-0.109547,-0.109066,-0.085122,-0.083265
1512,Bonjesta,Doxylamine Succinate/Vit B6,1,Overall,68138.43,6380.0,113.0,64.0,10.680005,602.994956,...,0.0,0.029006,0.039370,NaN,Other / Not classified,0.401086,-0.385599,0.439866,-0.535425,-0.020018
1322,Benlysta*,Belimumab,1,Overall,70896154.93,77119.2,18823.0,2561.0,953.608270,3766.464163,...,0.0,0.147805,0.068248,L04AG,Arthritis,0.248784,0.228632,0.259694,0.364809,0.275480

In [20]:
# melt the dataframe to long format by year for “Avg_Spnd_Per_Dsg_Unt_Wghtd_YYYY”
price_columns = [col for col in overall_df.columns if col.startswith('Avg_Spnd_Per_Dsg_Unt_Wghtd_')]

df_long = overall_df.melt(
    id_vars=['Brnd_Name', 'Gnrc_Name', 'Disease_Category'],
    value_vars=price_columns,
    var_name='Year_Column',
    value_name='Avg_Price'
)

df_long

,Brnd_Name,Gnrc_Name,Disease_Category,Year_Column,Avg_Price
0,Nivestym*,Filgrastim-Aafi,Other / Not classified,Avg_Spnd_Per_Dsg_Unt_Wghtd_2019,441.319845
1,Ultra Comfort,"Syringe And Needle,Insulin,1ml",Other / Not classified,Avg_Spnd_Per_Dsg_Unt_Wghtd_2019,0.208316
2,Niva-Plus,Multivit-Mins60/Iron Fum/Folic,Other / Not classified,Avg_Spnd_Per_Dsg_Unt_Wghtd_2019,0.409447
3,Nizatidine,Nizatidine,Other / Not classified,Avg_Spnd_Per_Dsg_Unt_Wghtd_2019,0.598778
4,Nityr,Nitisinone,Other / Not classified,Avg_Spnd_Per_Dsg_Unt_Wghtd_2019,NaN
...,...,...,...,...,...
17985,Lofena,Diclofenac Potassium,Arthritis,Avg_Spnd_Per_Dsg_Unt_Wghtd_2023,29.406938
17986,Bentyl,Dicyclomine HCl,Other / Not classified,Avg_Spnd_Per_Dsg_Unt_Wghtd_2023,18.068924
17987,Benicar,Olmesartan Medoxomil,Hypertension,Avg_Spnd_Per_Dsg_Unt_Wghtd_2023,10.953126
17988,Bonjesta,Doxylamine Succinate/Vit B6,Other / Not classified,Avg_Spnd_Per_Dsg_Unt_Wghtd_2023,12.463837
17989,Benlysta*,Belimumab,Arthritis,Avg_Spnd_Per_Dsg_Unt_Wghtd_2023,1241.817055

In [21]:
#extract Year from 'Year_Column' Name
df_long['Year'] = df_long['Year_Column'].str.extract(r'(\d{4})').astype(int)
#drop old 'Year_Column'
df_long = df_long.drop(columns=['Year_Column'])
df_long

,Brnd_Name,Gnrc_Name,Disease_Category,Avg_Price,Year
0,Nivestym*,Filgrastim-Aafi,Other / Not classified,441.319845,2019
1,Ultra Comfort,"Syringe And Needle,Insulin,1ml",Other / Not classified,0.208316,2019
2,Niva-Plus,Multivit-Mins60/Iron Fum/Folic,Other / Not classified,0.409447,2019
3,Nizatidine,Nizatidine,Other / Not classified,0.598778,2019
4,Nityr,Nitisinone,Other / Not classified,NaN,2019
...,...,...,...,...,...
17985,Lofena,Diclofenac Potassium,Arthritis,29.406938,2023
17986,Bentyl,Dicyclomine HCl,Other / Not classified,18.068924,2023
17987,Benicar,Olmesartan Medoxomil,Hypertension,10.953126,2023
17988,Bonjesta,Doxylamine Succinate/Vit B6,Other / Not classified,12.463837,2023
17989,Benlysta*,Belimumab,Arthritis,1241.817055,2023

In [22]:
#remove missing values where dugs don't have pricing data
df_long = df_long.dropna(subset=['Avg_Price'])
df_long

,Brnd_Name,Gnrc_Name,Disease_Category,Avg_Price,Year
0,Nivestym*,Filgrastim-Aafi,Other / Not classified,441.319845,2019
1,Ultra Comfort,"Syringe And Needle,Insulin,1ml",Other / Not classified,0.208316,2019
2,Niva-Plus,Multivit-Mins60/Iron Fum/Folic,Other / Not classified,0.409447,2019
3,Nizatidine,Nizatidine,Other / Not classified,0.598778,2019
6,Ultra Comfort,"Syringe-Needle,Insulin,0.5 Ml",Other / Not classified,0.200853,2019
...,...,...,...,...,...
17985,Lofena,Diclofenac Potassium,Arthritis,29.406938,2023
17986,Bentyl,Dicyclomine HCl,Other / Not classified,18.068924,2023
17987,Benicar,Olmesartan Medoxomil,Hypertension,10.953126,2023
17988,Bonjesta,Doxylamine Succinate/Vit B6,Other / Not classified,12.463837,2023
17989,Benlysta*,Belimumab,Arthritis,1241.817055,2023

In [26]:
# compute yearly average price for D3 plot on Average Price Trends per Year (2019-2023)
yearly_avg_price_trends = df_long.groupby('Year')['Avg_Price'].mean().reset_index()
yearly_avg_price_trends

   Year   Avg_Price
0  2019  305.331520
1  2020  342.898072
2  2021  365.146992
3  2022  474.442630
4  2023  563.020159

In [27]:
# export to csv for d3 plot
yearly_avg_price_trends.to_csv("yearly_avg_price_trends.csv", index=False)